iiii/Models/booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iiii.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class booking
    {
        public Nullable<int> RestaurantID { get; set; }
        public string RestaurantName { get; set; }
        public System.Guid BookingID { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public int userphone { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Dayselect { get; set; }
        [DataType(DataType.Time)]
        public System.TimeSpan selecttime { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}

iiii/Controllers/bookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iiii.Models;

namespace iiii.Controllers
{
    public class bookingsController : Controller
    {
        private forfoodiesEntities1 db = new forfoodiesEntities1();
        private int resid = 0;

        // GET: bookings
        public ActionResult Index(int id)
        {
            var bookings = db.bookings.Include(b => b.restaurant).Where(x => x.RestaurantID == id);
            resid = id;
            return View(bookings.ToList());
        }

        // GET: bookings/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: bookings/Create
        public ActionResult Create(int id=0)
        {
            //ViewBag.RestaurantID = new SelectList(db.restaurants, "Restaurant_id", "Restaurant_name");
            ViewBag.RestaurantID = id;
            return View();
        }

        // POST: bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RestaurantID,BookingID,username,useremail,userphone,Dayselect,selecttime")] booking booking)
        {
            if (ModelState.IsValid)
            {
                booking.BookingID = Guid.NewGuid();
                db.bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = booking.RestaurantID });
            }

            ViewBag.RestaurantID = booking.RestaurantID;
            return View(booking);
        }

        // GET: bookings/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestaurantID = new SelectList(db.restaurants, "Restaurant_id", "Restaurant_name", booking.RestaurantID);
            return View(booking);
        }

        // POST: bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RestaurantID,BookingID,username,useremail,userphone,Dayselect,selecttime")] booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RestaurantID = new SelectList(db.restaurants, "Restaurant_id", "Restaurant_name", booking.RestaurantID);
            return View(booking);
        }

        // GET: bookings/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }
            
        // POST: bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            booking booking = db.bookings.Find(id);
            db.bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = resid });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iiii/Views/bookings/Create.cshtml
@model iiii.Models.booking

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h2>booking</h2>
    @Html.ActionLink("Back to List", "Index", "bookings", new { id = ViewBag.RestaurantID }, new { @class = "btn btn-default" })
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.RestaurantID, "RestaurantID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.DropDownList("RestaurantID", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.RestaurantID, "", new { @class = "text-danger" })*@
            @ViewBag.RestaurantID
            <input type="hidden" value="@ViewBag.RestaurantID" name="RestaurantID" />
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.RestaurantName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RestaurantName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RestaurantName, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.useremail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.useremail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.useremail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.userphone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userphone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.userphone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dayselect, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Dayselect, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Dayselect, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.selecttime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.selecttime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.selecttime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

iiii/Views/bookings/Delete.cshtml
@model iiii.Models.booking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>booking</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.useremail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.useremail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userphone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userphone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dayselect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dayselect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.selecttime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.selecttime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.restaurant.Restaurant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.restaurant.Restaurant_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iiii/Views/bookings/Details.cshtml
@model iiii.Models.booking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RestaurantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RestaurantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.useremail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.useremail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userphone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userphone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dayselect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dayselect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.selecttime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.selecttime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.restaurant.Restaurant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.restaurant.Restaurant_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BookingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

iiii/Views/bookings/Edit.cshtml
@model iiii.Models.booking

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>booking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantID, "RestaurantID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RestaurantID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestaurantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RestaurantName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestaurantName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.BookingID)

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.useremail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.useremail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.useremail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userphone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userphone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userphone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dayselect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dayselect, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dayselect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.selecttime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.selecttime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.selecttime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iiii/Views/bookings/Index.cshtml
@model IEnumerable<iiii.Models.booking>

@{
    ViewBag.Title = "Index";
}

<h2>Booking lists</h2>


<table class="table">
    @Html.ActionLink("Back to List", "Index", "restaurants", null, new { @class = "btn btn-default" })
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.RestaurantName)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.useremail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userphone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dayselect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.selecttime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.restaurant.Restaurant_name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.RestaurantName)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.useremail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userphone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dayselect)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.selecttime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.restaurant.Restaurant_name)
            </td>
            <td>
               
                @Html.ActionLink("Delete", "Delete", new { id = item.BookingID })
            </td>
        </tr>
    }

</table>
<div style="height:400px;">
</div>