iiii/Models/restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iiii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restaurant()
        {
            this.bookings = new HashSet<booking>();
            this.menus = new HashSet<menu>();
        }
    
        public int Restaurant_id { get; set; }
        public string Restaurant_name { get; set; }
        public string Restaurant_type { get; set; }
        public string Restaurant_address { get; set; }
        public string Restaurant_about { get; set; }
        public int Restaurant_phone { get; set; }
        public System.TimeSpan OpenTime { get; set; }
        public System.TimeSpan closetime { get; set; }
        public string image1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menus { get; set; }
    }
}

iiii/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iiii.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        public ActionResult map(int rid)
        {
            ViewBag.id = rid;
            return View();
        }
    }
}

iiii/Controllers/restaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iiii.Models;

namespace iiii.Controllers
{
    public class restaurantsController : Controller
    {
        private forfoodiesEntities1 db = new forfoodiesEntities1();

        // GET: restaurants
        public ActionResult Index()
        {
            return View(db.restaurants.ToList());
        }

        // GET: restaurants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            restaurant restaurant = db.restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // GET: restaurants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Restaurant_id,Restaurant_name,Restaurant_type,Restaurant_address,Restaurant_about,Restaurant_phone,OpenTime,closetime,image1")] restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.restaurants.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurant);
        }

        // GET: restaurants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            restaurant restaurant = db.restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Restaurant_id,Restaurant_name,Restaurant_type,Restaurant_address,Restaurant_about,Restaurant_phone,OpenTime,closetime,image1")] restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurant);
        }

        // GET: restaurants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            restaurant restaurant = db.restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            restaurant restaurant = db.restaurants.Find(id);
            db.restaurants.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iiii/Views/restaurants/Create.cshtml
@model iiii.Models.restaurant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_about, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_about, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_about, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.closetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.closetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.closetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iiii/Views/restaurants/Delete.cshtml
@model iiii.Models.restaurant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_about)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_about)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.closetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.closetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iiii/Views/restaurants/Details.cshtml
@model iiii.Models.restaurant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_about)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_about)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.closetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.closetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Restaurant_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

iiii/Views/restaurants/Edit.cshtml
@model iiii.Models.restaurant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Restaurant_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_about, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_about, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_about, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.closetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.closetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.closetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iiii/Views/restaurants/Index.cshtml
@model IEnumerable<iiii.Models.restaurant>

@{
    ViewBag.Title = "list";

}

<h2>Restaurant Lists</h2>

<table class="table" border="0" style="width:45%;">
    @foreach (var item in Model)
    {
        if (item.Restaurant_id == 1 || item.Restaurant_id == 3 || item.Restaurant_id == 5)
        {
            <tr>
                <td style="border-top-color:black;border-top-width:3px;">
                    ID
                </td>
                <td style="border-top-color:black;border-top-width:3px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_id)
                </td>
                <td width="140" align="center" rowspan="3" style="border-top-color:black;border-top-width:3px;">
                    <img src="~/images/@Url.Content(item.image1)" height="150" width="180" />
                    <br />
                    <input type="button" value="Menu" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("Index", "menus", new { id = item.Restaurant_id, resname = item.Restaurant_name })'" />
                    <input type="button" value="Booking" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("Create", "bookings", new { id = item.Restaurant_id })'" />
                    <input type="button" value="Direction" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("map", "Map",new {rid=item.Restaurant_id})'" />
                </td>
            </tr>
            <tr>
                <td>
                    Name
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant_name)
                </td>
            </tr>
            <tr>
                <td>
                    Type
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant_type)
                </td>
            </tr>
            <tr>
                <td>
                    Location
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant_address)
                </td>
            </tr>

            <tr>
                <td>
                    About
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant_about)
                </td>
            </tr>

            <tr>
                <td>
                    Contact
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant_phone)
                </td>
            </tr>

            <tr>
                <td>
                    Open
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OpenTime)
                </td>
            </tr>
            <tr>
                <td style="padding-bottom:50px;">
                    Close
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.closetime)
                </td>
            </tr>
        }
    }
</table>
<table class="table" border="0" align="right" style="width:49%;margin-top:-130%;">
    @foreach (var item in Model)
    {
        if (item.Restaurant_id == 2 || item.Restaurant_id == 4 || item.Restaurant_id == 6)
        {
            <tr>
                <td style="border-top-color:black;border-top-width:3px;">
                    ID
                </td>
                <td style="border-top-color:black;border-top-width:3px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_id)
                </td>
                <td width="140" align="center" rowspan="3" style="border-top-color:black;border-top-width:3px;">
                    <img src="~/images/@Url.Content(item.image1)" height="150" width="180" />
                    <br />
                    <input type="button" value="Menu" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("Index", "menus", new { id = item.Restaurant_id, resname = item.Restaurant_name })'" />
                    <input type="button" value="Booking" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("Create", "bookings",new { id = item.Restaurant_id})'" />
                    <input type="button" value="Direction" id="btn1" style="margin-top:5px;border-radius:1px;" onclick="location.href='@Url.Action("map", "Map",new {rid=item.Restaurant_id})'" />
                </td>
            </tr>
            <tr>
                <td style="border-top-color:black;border-top-width:2px;">
                    Name
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_name)
                </td>
            </tr>
            <tr>
                <td style="border-top-color:black;border-top-width:2px;">
                    Type
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_type)
                </td>
            </tr>
            <tr>
                <td style="border-top-color:black;border-top-width:2px;">
                    Location
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_address)
                </td>
            </tr>

            <tr>
                <td style="border-top-color:black;border-top-width:2px;">
                    About
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_about)
                </td>
            </tr>

            <tr>
                <td style="border-top-color:black;border-top-width:2px;">
                    Contact
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.Restaurant_phone)
                </td>
            </tr>

            <tr>
                <td style="border-top-color:black;border-top-width:2px;"> 
                    Open
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.OpenTime)
                </td>
            </tr>
            <tr>
                <td style="padding-bottom:50px;border-top-color:black;border-top-width:2px;">
                    Close
                </td>
                <td style="border-top-color:black;border-top-width:2px;">
                    @Html.DisplayFor(modelItem => item.closetime)
                </td>
            </tr>
        }
    }
</table>